version: "3.10"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
      - ./logs/nginx/error:/var/log/nginx/error
      - ./logs/nginx/access:/var/log/nginx/access
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    logging:
      driver: "local"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    logging:
      driver: "local"

  postgres:
    image: postgres:15
    container_name: db
    command: -p 5432
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER:?err}
      - POSTGRES_PASSWORD=${DB_PASS:?err}
      - POSTGRES_DB=${DB_NAME:?err}
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data

